// Generated by https://quicktype.io

export interface Points {
    data:    Accionable[];
}

export interface Accionable{
    id_accionable:    number;
    id_learning_card: number;
    contenido:        string;
    impacto:          number;
    esfuerzo:         number;
    realizado:        boolean;
}
