// Generated by https://quicktype.io

export interface Points {
    data:    Accionable[];
}

export interface Accionable{
    idF?:             string; // Solo para uso en frontend, no se envía al backend
    id_accionable?:    number;
    id_learning_card: number;
    contenido:        string;
    impacto:          number;
    esfuerzo:         number;
    realizado:        boolean;
}
